version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:latest
    privileged: true
    user: root
    ports:
      - 8082:8080
      - 50000:50000
    container_name: jenkins-cont
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

  nginx_image:
    build: ./Dockerfile
    image: nginx_image
    container_name: "nginx_cont"
    ports:
      - "8081:80"

volumes:
  jenkins_home: